name: Publish image to the Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set TAG variable
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build tarantool/doc-builder fat image
        run: |
          docker build \
            -t tarantool/doc-builder:fat-${TAG} \
            -t tarantool/doc-builder:fat .

      - name: Build tarantool/doc-builder slim image
        run: |
          docker build -f Dockerfile-slim \
            -t tarantool/doc-builder:slim-${TAG} \
            -t tarantool/doc-builder:slim .

      - name: Check tags
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push built docker image
        run: docker push tarantool/doc-builder --all-tags
